### PR TITLE
I made a webapp with Vue.js

### PR DESCRIPTION
**Pull request by NathanBland**
https://nathanbland.github.io/temperature-converter/

### CODE REVIEW

**Comment by keawade** [comment]
[cough cough](http://chris.beams.io/posts/git-commit/)

Actually, this article might be of use as extra reading or something for your class, @barberboy.

**Comment by Malachi-M** [comment]
Can we get some layout consistency in this hizous! Some sort of vertical rhythm based on something. ORDER! Give this interface ORDER!

**Comment by Malachi-M** [comment]
Last thing from me. Exactly how many files did it take to achieve this?

**Comment by NathanBland** [comment]
> Can we get some layout consistency in this hizous! Some sort of vertical rhythm based on something. ORDER! Give this interface ORDER!

If you have something specific thing let me know.. I made this in an hour. UI didn't get a ton of focus.. just did a mobile view really

**Comment by NathanBland** [comment]
Of course the time taken shouldn't be an excuse @Malachi-M

**Comment by barberboy** [comment]
@NathanBland: Don't mind the haters. @Malachi-M can put up or shut up.

**Comment by keawade** [comment]
Ohhhhhhhh

**Comment by barberboy** [comment]
I'm not sure what the browser support is for Vue, but I wasn't able to run this on my phone (iPhone 4 :grimacing:). Things in the browser looked good!

**Comment by NathanBland** [comment]
Out of curiosity, did the entire page not display, or did the form simply not seem to work @barberboy?

If I had to guess I'd say it's an issue with the `fetch` pollyfill, aka the lack of support in safari :wink:

**Comment by barberboy** [comment]
Page displayed, but nothing happened after clicking "SUBMIT".

**Comment by NathanBland** [comment]
I figured as much... That's less of a `vue.js` issue and more of a `fetch` or `promise` issue on safari.. If I had used [`vue-resource`](https://github.com/vuejs/vue-resource) it would probably work fine, but this uses a [`fetch` pollyfill](https://github.com/matthew-andrews/isomorphic-fetch). 

That's what I get for being lazy and not wanting to do `xhr` style requests..

Edit: a different [fetch pollyfill](https://github.com/github/fetch#browser-support) claims support for safari so I may give that a shot..

**Comment by Malachi-M** [comment]
@NathanBland Mind what you mind. Don't let @barberboy goad you into putting up something that  isn't ready.

**Comment by barberboy** [comment]
This is super sweet. 👍  💯  😍

**Pull request closed without merging**
